version: '3'
services:
  task-frontend:
    build:
      context: .
      dockerfile: deploy/docker/local/linux/node/Dockerfile
    ports:
      - 8080:3000
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    command: npm run dev -- --host
    restart: unless-stopped
